# Generated by Django 5.2.8 on 2025-12-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_name', models.CharField(max_length=40)),
                ('Project_name', models.CharField(max_length=30)),
                ('Lead_contact', models.EmailField(max_length=30)),
                ('member1', models.CharField(max_length=40)),
                ('member2', models.CharField(max_length=40)),
                ('member3', models.CharField(max_length=40)),
            ],
        ),
    ]
