# Generated by Django 5.2.8 on 2025-12-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='Lead_contact',
            new_name='lead_contact',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Team_name',
            new_name='member4',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Project_name',
            new_name='project_name',
        ),
        migrations.AddField(
            model_name='registration',
            name='team_name',
            field=models.CharField(default=-5, max_length=40),
            preserve_default=False,
        ),
    ]
